### ISSUE TITLE
Alerts are not properly formatted when in non-full-width position

### ISSUE THREAD

**Issue by edward-shen** [edward-shen/MMM-MBTA#1]
When `showAlerts` is `true`, alerts will not properly format themselves such that they do not take the full width when in a non-full-width position, such as `top_right`.

As of writing this, and spending a few hours on trying to get this to work, I've given up.
I would heavily appreciate a pull request.

**Comment by andywaplinger** [comment]
From what I can tell, it seems like the root of the issue stems from MagicMirror's CSS. Maybe it's possible to manage it within MMM-MBTA's CSS, but I couldn't figure out a good way.
