### ISSUE TITLE
Problem with multiple buses at one stop

### ISSUE THREAD

**Issue by joelman** [edward-shen/MMM-MBTA#13]
Great work on this module!  My stop is "Broadway @ Main St".  There are two buses which stop there: the 89 and the 101.  The module seems to mix up the routes and destinations, showing for example, "Clarendon Hill | 101", instead of "Clarendon Hill | 89".  [See picture](https://i.imgur.com/O61XTaL.png)

Updating this line seems to fix the problem: 

`diff --git a/MMM-MBTA.js b/MMM-MBTA.js
index 613d4c0..d75add6 100644
--- a/MMM-MBTA.js
+++ b/MMM-MBTA.js
@@ -225,7 +225,7 @@ Module.register("MMM-MBTA", {
                             descCell.innerHTML += " | CT3";
                             break;
                         default:
-                            descCell.innerHTML += " | " + routeId;
+                            descCell.innerHTML += " | " + this.stationData[i].routeId;
                     }
                 }
                 descCell.className = "align-left bright";
`
[See picture](https://i.imgur.com/TD6aZ9m.png)

Cheers,
Joel

**Comment by edward-shen** [comment]
I just implemented this; let me know if that fixes your problem!

**Comment by joelman** [comment]
Looking good, my man.  Thanks!

**Comment by edward-shen** [comment]
Great! Feel free to reopen or create a new issue if you have any more issues.
