### ISSUE TITLE
Config check - showing nothing coming soon...

### ISSUE THREAD

**Issue by nakulbende** [edward-shen/MMM-MBTA#17]
Hello, I have the following config on my file: 
```
		{
			module: 'MMM-MBTA',
			position: 'bottom_left', // This can be any of the regions.
			header: "MBTA: Davis",
			config: {
				apikey: 'XXXXXXX',
				updateInterval: 30,
				stations: 'Davis Square": "place-davis',
				formatETA: 'true',
				showOnly: ["Subway", "Bus"],
				colorIcons: 'true',
				direction: 'Inbound',
				noETAToBack: 'false'
			}
		},
```

But I am getting a nothing coming soon error. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/8712050/71262694-53c2a180-230e-11ea-990d-6c5b0e971242.png)

On a seperate note, how does the stations field look if I want to include two stations? Say `Davis Square": "place-davis` and `Main St @ Emerson Rd": "8823`

**Comment by edward-shen** [comment]
Hey, sorry about the late response,

Your config is incorrect: the `stations` key should look something like this:
```
stations: ['Davis Square'],
```

I don't know if multiple stations are supported, but you can try with `['Davis Square', 'Main St @ Emerson Rd']`.

**Comment by edward-shen** [comment]
Closing due to age. Feel free to reopen if you still have problems.
