### ISSUE TITLE
Showing default bus routes after configuring Kendall Sq

### ISSUE THREAD

**Issue by jamiec117** [edward-shen/MMM-MBTA#2]
Got my API key today and the module itself works but it keeps showing the list of default routes even after i've configured it to Kendall Sq.

Also, i'm trying to get the bus schedule for the 64 inbound to Kendall from Oak Square (Brighton). Am i choosing the right route? Is my bus available in this module?

`
{
    		    module: 'MMM-MBTA',
    		    position: 'top_right',
    		    header: "BUS",
    		    config: {
        	    	apikey: '#########',
			stations: ["Kendall Square"],
        		}
    		},
`

**Comment by edward-shen** [comment]
@jamiec117 Delete your API key from your post Now. Like, ***right now***. You should never show any api/secret/etc. key publicly.

I'll take a look at this in a sec, but you gotta delete that key right now. Change it to some filler text, even. Just make sure it's not public.

**Comment by jamiec117** [comment]
Wow i tried re-pasting because it wasn't formatting it correctly and totally forgot thanks for the heads up. It actually might be pulling the correct data but i was confused because i was only seeing train stops but it makes sense since it's the middle of the night.

Question is: can I have it only display my stop/will it show that in the list of stops based on the time & my location?

**Comment by edward-shen** [comment]
You can make it so that it only displays the bus stop using the `showOnly` config option:
```js
{
    module: 'MMM-MBTA',
    position: 'top_right',
    header: "BUS",
    config: {
        apikey: '#########',
        stations: ["Kendall Square"],
        showOnly: ["Bus"],
    }
},
```
With that option in your config, it will only show buses at your stop, which should resolve your primary issue.

**Comment by edward-shen** [comment]
Please tell me if that didn't solve your issue.

------

Regarding your other questions: unfortunately, I haven't considered implementing a direction filter nor a time-based filter.

Fortunately, though, it's pretty simple to implement the direction filter, since our data is in the form of:
```
"mode":[ {
  "route_type":"3",
  "mode_name":"Bus",
  "route":[ {
    "route_id":"39",
    "route_name":"39",
    "direction":[ {
      "direction_id":"0",
      "direction_name":"Outbound",
      "trip":[ {
        "trip_id":"35272365",
        "trip_name":"1:05 am from Back Bay Station to Forest Hills Station",
        "trip_headsign":"Forest Hills",
        "sch_arr_dt":"1508303400",
        "sch_dep_dt":"1508303400",
        "pre_dt":"1508304089",
        "pre_away":"363",
        "vehicle": {
          "vehicle_id":"y1704",
          "vehicle_lat":"42.3496360778809",
          "vehicle_lon":"-71.0722808837891",
          "vehicle_bearing":"341",
          "vehicle_speed":"0",
          "vehicle_timestamp":"1508303675",
          "vehicle_label":"1704"
        }
      }]
    }]
  }]
}]
```

We can probably just make a direction filter for `"Outbound"` or `"Inbound"`, but I probably won't have much time to do it soon, since it's midterm week(s).

Time based indication would be rather difficult, but perhaps we can do something like
```
config: {
  ...
  timeFilter: [ { timeStart: "12:40PM", timeEnd:  "3:30PM", filter: ["Bus"] },
                { timeStart:  "3:31PM", timeEnd: "12:00AM", filter: ["Bus", "Subway"] }, ]
  ...
}
```

As for implementation difficulty, I would have no idea how to do that without spending a good hour figuring it out.

These are both two good features to have! If you want the features out faster than I can work on them, please feel free to fork + do a pull request. Otherwise, you may need to wait for a weekend for me to work on it.

**Comment by jamiec117** [comment]
Hey Edward,

The module is working and I am now only seeing buses thanks! If the bus’ name is “Oak Square” (where I get on) in the list, is that leaving from oak square to Kendall or is it the opposite? 

Also noticed the timing of it was a couple minutes different from the mbta app which isn’t a huge deal but is that normal?

**Comment by edward-shen** [comment]
It follows the same convention as the MBTA, so Oakland would be going towards Oakland, similarly how if you see a ticker sign that says Lechmere on the T, it's going to Lechmere. 

A couple of minutes off is disturbing. My data is from the API, but I can check it out as well.

**Comment by edward-shen** [comment]
Closing in favor of #4, #5, #6.

Please feel free to submit a new issue if any more problems occur!
