### ISSUE TITLE
Add direction filter

### ISSUE THREAD

**Issue by edward-shen** [edward-shen/MMM-MBTA#5]
See #2.

**Comment by edward-shen** [comment]
Copy-pasted from the discussion:
Fortunately, though, it's pretty simple to implement the direction filter, since our data is in the form of:
```json
"mode":[ {
  "route_type":"3",
  "mode_name":"Bus",
  "route":[ {
    "route_id":"39",
    "route_name":"39",
    "direction":[ {
      "direction_id":"0",
      "direction_name":"Outbound",
      "trip":[ {
        "trip_id":"35272365",
        "trip_name":"1:05 am from Back Bay Station to Forest Hills Station",
        "trip_headsign":"Forest Hills",
        "sch_arr_dt":"1508303400",
        "sch_dep_dt":"1508303400",
        "pre_dt":"1508304089",
        "pre_away":"363",
        "vehicle": {
          "vehicle_id":"y1704",
          "vehicle_lat":"42.3496360778809",
          "vehicle_lon":"-71.0722808837891",
          "vehicle_bearing":"341",
          "vehicle_speed":"0",
          "vehicle_timestamp":"1508303675",
          "vehicle_label":"1704"
        }
      }]
    }]
  }]
}]
```
We can probably just make a direction filter for "Outbound" or "Inbound", but I probably won't have much time to do it soon, since it's midterm week(s).

**Comment by edward-shen** [comment]
Turns out I already extract Inbound/Outbound but never did anything with it. Oops.

This should just be easy as writing a generic filter.

**Comment by jamiec117** [comment]
This looks like a great addition thanks for tasking this.

**Comment by gmichaela** [comment]
Interested in this, if you need help implementing, let me know.

**Comment by edward-shen** [comment]
Feel free to make a PR! I'm unfortunately not actively developing this module, but I'd be happy to review and merge your code!

**Comment by gmichaela** [comment]
> Feel free to make a PR! I'm unfortunately not actively developing this module, but I'd be happy to review and merge your code!

Done #16
